#============================================================================
# DATABASE
#============================================================================
db:
  name : test_security
  host : localhost
  port : 5432
  username : postgres
  password : pgadmin
  auto-reconnect : true
  ssl : false
#============================================================================
# LOG FILE PATH
#============================================================================
log :
  file :
    path : /home/fauzi/sar/sar.log